{
    "openapi": "3.0.1",
    "info": {
        "title": "azul-indexer-dev",
        "version": "3.2",
        "description": "\nThis is the internal API for Azul's indexer component.\n\n\n## Contact us\n\nFor technical support please file an issue at\n[GitHub](https://github.com/DataBiosphere/azul/issues) or email\n`azul-group@ucsc.edu`. To report a security concern or misconduct please email\n`azul-group@ucsc.edu`.\n"
    },
    "paths": {
        "/": {
            "get": {
                "summary": "Redirect to the Swagger UI for interactive use of this REST API",
                "tags": [
                    "Auxiliary"
                ],
                "responses": {
                    "301": {
                        "description": "A redirect to the Swagger UI"
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                }
            }
        },
        "/swagger/index.html": {
            "get": {
                "summary": "The Swagger UI for interactive use of this REST API",
                "tags": [
                    "Auxiliary"
                ],
                "responses": {
                    "200": {
                        "description": "The response body is an HTML page containing the Swagger UI"
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                }
            }
        },
        "/swagger/swagger-initializer.js": {
            "get": {
                "summary": "Used internally by the Swagger UI",
                "tags": [
                    "Auxiliary"
                ],
                "responses": {
                    "200": {
                        "description": "The response body is JavaScript used internally by the Swagger UI"
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                }
            }
        },
        "/swagger/{file}": {
            "parameters": [
                {
                    "name": "file",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "string"
                    },
                    "description": "The name of a static file to be returned"
                }
            ],
            "get": {
                "summary": "Static files needed for the Swagger UI",
                "tags": [
                    "Auxiliary"
                ],
                "responses": {
                    "200": {
                        "description": "The response body is the contents of the requested file"
                    },
                    "404": {
                        "description": "The requested file does not exist"
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                }
            }
        },
        "/openapi.json": {
            "get": {
                "summary": "Return OpenAPI specifications for this REST API",
                "description": "\nThis endpoint returns the [OpenAPI specifications]'\n(https://github.com/OAI/OpenAPI-Specification) for this REST\nAPI. These are the specifications used to generate the page\nyou are visiting now.\n",
                "responses": {
                    "200": {
                        "description": "200 response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "openapi": {
                                            "type": "string"
                                        },
                                        "info": {
                                            "type": "object",
                                            "properties": {},
                                            "additionalProperties": false
                                        },
                                        "tags": {
                                            "type": "object",
                                            "properties": {},
                                            "additionalProperties": false
                                        },
                                        "servers": {
                                            "type": "object",
                                            "properties": {},
                                            "additionalProperties": false
                                        },
                                        "paths": {
                                            "type": "object",
                                            "properties": {},
                                            "additionalProperties": false
                                        },
                                        "components": {
                                            "type": "object",
                                            "properties": {},
                                            "additionalProperties": false
                                        }
                                    },
                                    "required": [
                                        "openapi",
                                        "info",
                                        "tags",
                                        "servers",
                                        "paths",
                                        "components"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        }
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                },
                "tags": [
                    "Auxiliary"
                ]
            }
        },
        "/version": {
            "get": {
                "summary": "Describe current version of this REST API",
                "tags": [
                    "Auxiliary"
                ],
                "responses": {
                    "200": {
                        "description": "Version endpoint is reachable.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "git": {
                                            "type": "object",
                                            "properties": {
                                                "commit": {
                                                    "type": "string"
                                                },
                                                "dirty": {
                                                    "type": "boolean"
                                                }
                                            },
                                            "required": [
                                                "commit",
                                                "dirty"
                                            ],
                                            "additionalProperties": false
                                        }
                                    },
                                    "required": [
                                        "git"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        }
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                }
            }
        },
        "/robots.txt": {
            "get": {
                "summary": "Robots Exclusion Protocol",
                "tags": [
                    "Auxiliary"
                ],
                "responses": {
                    "200": {
                        "description": "\nThe robots.txt resource according to\n[RFC9309](https://datatracker.ietf.org/doc/html/rfc9309)\n"
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                }
            }
        },
        "/health": {
            "get": {
                "summary": "Complete health check",
                "description": "\nHealth check of the indexer REST API and all\nresources it depends on. This may take long time to complete\nand exerts considerable load on the API. For that reason it\nshould not be requested frequently or by automated\nmonitoring facilities that would be better served by the\n[`/health/fast`](#operations-Auxiliary-get_health_fast) or\n[`/health/cached`](#operations-Auxiliary-get_health_cached)\nendpoints.\n",
                "responses": {
                    "200": {
                        "description": "\nThe checked resources\nare healthy.\n\nThe response consists of the following keys:\n\n* `other_lambdas` \nIndicates whether the companion REST API responds to HTTP requests.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `api_endpoints` \nIndicates whether important service API endpoints are operational.\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`true`.\n\n\nAll of the nested `up` keys\nare `true`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                true
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    true
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "other_lambdas": {},
                                    "queues": {},
                                    "progress": {},
                                    "api_endpoints": {},
                                    "elasticsearch": {},
                                    "up": true
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "\nAt least one of the checked resources\nis not healthy.\n\nThe response consists of the following keys:\n\n* `other_lambdas` \nIndicates whether the companion REST API responds to HTTP requests.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `api_endpoints` \nIndicates whether important service API endpoints are operational.\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`false`.\n\n\nAt least one of the nested `up` keys\nis `false`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                false
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    false
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "other_lambdas": {},
                                    "queues": {},
                                    "progress": {},
                                    "api_endpoints": {},
                                    "elasticsearch": {},
                                    "up": false
                                }
                            }
                        }
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                },
                "tags": [
                    "Auxiliary"
                ]
            }
        },
        "/health/basic": {
            "get": {
                "summary": "Basic health check",
                "description": "\nHealth check of only the REST API itself, excluding other\nresources that it depends on. A 200 response indicates that\nthe indexer is reachable via HTTP(S) but nothing\nmore.\n",
                "responses": {
                    "200": {
                        "description": "\nThe checked resources\nare healthy.\n\nThe response consists of the following keys:\n\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`true`.\n\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                true
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    true
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "up": true
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "\nAt least one of the checked resources\nis not healthy.\n\nThe response consists of the following keys:\n\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`false`.\n\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                false
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    false
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "up": false
                                }
                            }
                        }
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                },
                "tags": [
                    "Auxiliary"
                ]
            }
        },
        "/health/cached": {
            "get": {
                "summary": "Cached health check for continuous monitoring",
                "description": "\nReturn a cached copy of the\n[`/health/fast`](#operations-Auxiliary-get_health_fast)\nresponse. This endpoint is optimized for continuously\nrunning, distributed health monitors such as Route 53 health\nchecks. The cache ensures that the indexer is not\noverloaded by these types of health monitors. The cache is\nupdated every minute.\n",
                "responses": {
                    "200": {
                        "description": "\nThe checked resources\nare healthy.\n\nThe response consists of the following keys:\n\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`true`.\n\n\nAll of the nested `up` keys\nare `true`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                true
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    true
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "elasticsearch": {},
                                    "queues": {},
                                    "progress": {},
                                    "up": true
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "\nAt least one of the checked resources\nis not healthy.\n\nThe response consists of the following keys:\n\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`false`.\n\n\nAt least one of the nested `up` keys\nis `false`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                false
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    false
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "elasticsearch": {},
                                    "queues": {},
                                    "progress": {},
                                    "up": false
                                }
                            }
                        }
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                },
                "tags": [
                    "Auxiliary"
                ]
            }
        },
        "/health/fast": {
            "get": {
                "summary": "Fast health check",
                "description": "\nPerformance-optimized health check of the REST API and other\ncritical resources tht it depends on. This endpoint can be\nrequested more frequently than\n[`/health`](#operations-Auxiliary-get_health) but\nperiodically scheduled, automated requests should be made to\n[`/health/cached`](#operations-Auxiliary-get_health_cached).\n",
                "responses": {
                    "200": {
                        "description": "\nThe checked resources\nare healthy.\n\nThe response consists of the following keys:\n\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`true`.\n\n\nAll of the nested `up` keys\nare `true`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                true
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    true
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "elasticsearch": {},
                                    "queues": {},
                                    "progress": {},
                                    "up": true
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "\nAt least one of the checked resources\nis not healthy.\n\nThe response consists of the following keys:\n\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`false`.\n\n\nAt least one of the nested `up` keys\nis `false`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                false
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    false
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "elasticsearch": {},
                                    "queues": {},
                                    "progress": {},
                                    "up": false
                                }
                            }
                        }
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                },
                "tags": [
                    "Auxiliary"
                ]
            }
        },
        "/health/{keys}": {
            "parameters": [
                {
                    "name": "keys",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": [
                                "api_endpoints",
                                "elasticsearch",
                                "other_lambdas",
                                "progress",
                                "queues"
                            ]
                        }
                    },
                    "description": "\nA comma-separated list of keys selecting the health\nchecks to be performed. Each key corresponds to an\nentry in the response.\n"
                }
            ],
            "get": {
                "summary": "Selective health check",
                "description": "\nThis endpoint allows clients to request a health check on a\nspecific set of resources. Each resource is identified by a\n*key*, the same key under which the resource appears in a\n[`/health`](#operations-Auxiliary-get_health) response.\n",
                "responses": {
                    "200": {
                        "description": "\nThe checked resources\nare healthy.\n\nThe response consists of the following keys:\n\n* `other_lambdas` \nIndicates whether the companion REST API responds to HTTP requests.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `api_endpoints` \nIndicates whether important service API endpoints are operational.\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`true`.\n\n\nAll of the nested `up` keys\nare `true`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                true
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    true
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "other_lambdas": {},
                                    "queues": {},
                                    "progress": {},
                                    "api_endpoints": {},
                                    "elasticsearch": {},
                                    "up": true
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "\nAt least one of the checked resources\nis not healthy.\n\nThe response consists of the following keys:\n\n* `other_lambdas` \nIndicates whether the companion REST API responds to HTTP requests.\n* `queues` \nReturns information about the SQS queues used by the indexer.\n* `progress` \nThe number of Data Store bundles pending to be indexed and the number\nof index documents in need of updating.\n* `api_endpoints` \nIndicates whether important service API endpoints are operational.\n* `elasticsearch` \nIndicates whether the Elasticsearch cluster is responsive.\n* `up` \nindicates the overall result of the health check\n\n\nThe top-level `up` key of the response is\n`false`.\n\n\nAt least one of the nested `up` keys\nis `false`.\n",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "up": {
                                            "type": "boolean",
                                            "enum": [
                                                false
                                            ]
                                        }
                                    },
                                    "required": [
                                        "up"
                                    ],
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "up": {
                                                "type": "boolean",
                                                "enum": [
                                                    false
                                                ]
                                            }
                                        },
                                        "required": [
                                            "up"
                                        ],
                                        "additionalProperties": true
                                    }
                                },
                                "example": {
                                    "other_lambdas": {},
                                    "queues": {},
                                    "progress": {},
                                    "api_endpoints": {},
                                    "elasticsearch": {},
                                    "up": false
                                }
                            }
                        }
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                },
                "tags": [
                    "Auxiliary"
                ]
            }
        },
        "/{catalog}/{action}": {
            "post": {
                "tags": [
                    "Indexing"
                ],
                "summary": "Notify the indexer to perform an action on a bundle",
                "description": "\nQueue a bundle for addition to or deletion from the index.\n\nThe request must be authenticated using HMAC via the ``signature``\nheader. Each Azul deployment has its own unique HMAC key. The HMAC\ncomponents are the request method, request path, and the SHA256\ndigest of the request body.\n\nA valid HMAC header proves that the client is in possession of the\nsecret HMAC key and that the request wasn't tampered with while\ntravelling between client and service, even though the latter is not\nstrictly necessary considering that TLS is used to encrypt the\nentire exchange. Internal clients can obtain the secret key from the\nenvironment they are running in, and that they share with the\nservice. External clients must have been given the secret key. The\nnow-defunct DSS was such an external client. The Azul indexer\nprovided the HMAC secret to DSS when it registered with DSS to be\nnotified about bundle additions/deletions. These days only internal\nclients use this endpoint.\n",
                "requestBody": {
                    "description": "Contents of the notification",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "bundle_fqid": {
                                        "type": "object",
                                        "properties": {
                                            "uuid": {
                                                "type": "string"
                                            },
                                            "version": {
                                                "type": "string"
                                            },
                                            "source": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string"
                                                    },
                                                    "spec": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "id",
                                                    "spec"
                                                ],
                                                "additionalProperties": false
                                            }
                                        },
                                        "required": [
                                            "uuid",
                                            "version",
                                            "source"
                                        ],
                                        "additionalProperties": false
                                    }
                                },
                                "required": [
                                    "bundle_fqid"
                                ],
                                "additionalProperties": false
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "catalog",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "dcp2"
                            ]
                        },
                        "description": "The name of the catalog to notify."
                    },
                    {
                        "name": "action",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "add",
                                "delete"
                            ]
                        },
                        "description": "Which action to perform."
                    },
                    {
                        "name": "signature",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "description": "HMAC authentication signature."
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notification was successfully queued for processing"
                    },
                    "400": {
                        "description": "Request was rejected due to malformed parameters"
                    },
                    "401": {
                        "description": "Request lacked a valid HMAC header"
                    },
                    "504": {
                        "description": "\nRequest timed out. When handling this response, clients\nshould wait the number of seconds specified in the\n`Retry-After` header and then retry the request.\n"
                    }
                }
            }
        }
    },
    "tags": [],
    "servers": [
        {
            "url": "http://localhost/"
        }
    ]
}